apiVersion: v1
kind: Pod
metadata:
  name: testpod
spec:
  containers:
    - name: container1
      image: nginx
      command: ["/bin/bash", "-c", "while true; do echo 'Hello Kubernetes';sleep 5;done"]
    - name: container2
      image: busybox
      command: ["/bin/sh","-c", "while true; do echo 'Second Pod is still running';sleep 3;done"]
  restartPolicy: Never