apiVersion: v1
kind: Pod
metadata:
  name: nginx-tol
  labels:
    app: nginx
spec:
  containers:
  - image: nginx
    name: nginx-pod
    ports:
    - containerPort: 80
  tolerations:
  - key: "frontend"
    operator: "Exists"
    effect: "NoSchedule"
