apiVersion: v1
kind: Pod
metadata:
  labels:
  name: app
spec:
  containers:
  - image: nginx
    name: app
    ports:
    - containerPort: 80
    resources:
      requests:
       cpu: "200m"
       memory: "2Gi"