apiVersion: v1
kind: Service
metadata:
  name: bmi-app-service
spec:
  selector:
    app: bmi-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 5000
    nodePort: 30001 
