apiVersion: apps/v1
kind: Deployment
metadata:
  name: bmi-deployment
  labels:
    app: bmi-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bmi-app
  template:
    metadata:
      labels:
        app: bmi-app
    spec:
      containers:
        - name: bmi
          image: pawanksry97/bmi
          ports:
          - containerPort: 5000
