apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: index-vol
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: index-vol
        configMap:
          name: nginx-index

