apiVersion: v1
kind: Pod
metadata:
  name: business-app
spec:
  volumes:
  - name: logs-volume
    emptyDir: {}   # Empty directory in Pod with read/write access. Persisted for only the lifespan of a Pod
  containers:
  - image: nginx
    name: business-app
    volumeMounts:
    - mountPath: /var/logs
      name: logs-volume