apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
    - name: mybusybox-mc
      image: busybox
      command: ["/bin/bash", "-c", "while true; do sleep 9999; done"]
      volumeMounts:
        - mountPath: /tmp/storage
          name: myvolume-mc
    - name: mynginx-mc
      image: nginx
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: myvolume-mc
          readOnly: true
      ports:
        - containerPort: 80
          protocol: TCP
  volumes:
    - name: myvolume-mc
      emptyDir: {}